server:
  address: 0.0.0.0
activemq:
  brokerUrl: ${ACTIVEMQ_BROKER_URL:vm://localhost:61616}
queue:
  name: ${QUEUE_NAME:ELC-Queue}
worker:
  name: ${HOSTNAME:worker1}
  enabled: ${WORKER_ENABLED:true}
store:
  enabled: ${STORE_ENABLED:true}
logging:
  level:
    root: debug