apiVersion: v1
kind: Namespace
metadata:
  name: sis-demo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: sis-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: seenidockerregistry.azurecr.io/elc-service:0.0.2-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: ACTIVEMQ_BROKER_URL
              value: "tcp://queue:61616"
            - name: STORE_ENABLED
              value: "true"
            - name: WORKER_ENABLED
              value: "false"
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          resources:
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sis-demo
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: frontend
